### PR TITLE
Add void + cancel methods and enable partial refunds

### LINKED ISSUE #37: Canceling an Order in the admin backend raises a NotImplementedError in Spree::Admin::OrdersController#cancel
When canceling an Order in the backend the following error is raised:

NotImplementedError in Spree::Admin::OrdersController#cancel
You must implement cancel method for this payment method.

Extracted source (around line #69):
    def cancel(response)
      raise ::NotImplementedError, 'You must implement cancel method for this payment method.'
    end
  end
end

Rails.root: /app

vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.4/app/models/spree/payment_method.rb:69:in `cancel'
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.4/app/models/spree/payment/processing.rb:72:in `cancel!'
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.4/app/models/spree/order.rb:608:in `block in after_cancel'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/relation/delegation.rb:46:in `each'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/relation/delegation.rb:46:in `each'
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.4/app/models/spree/order.rb:608:in `after_cancel'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/eval_helpers.rb:58:in `evaluate_method'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:192:in `block in run_methods'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:191:in `each'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:191:in `run_methods'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:159:in `call'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:394:in `block (2 levels) in after'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:394:in `each'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:394:in `block in after'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:392:in `catch'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:392:in `after'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:195:in `run_callbacks'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:127:in `run_callbacks'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:63:in `block (2 levels) in perform'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:63:in `catch'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:63:in `block in perform'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:186:in `within_transaction'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:62:in `perform'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:163:in `perform'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:155:in `fire'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:219:in `block in add_actions'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/machine.rb:725:in `call'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/machine.rb:725:in `block (2 levels) in define_helper'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:224:in `block in add_actions'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/machine.rb:725:in `call'
vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/machine.rb:725:in `block (2 levels) in define_helper'
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.4/app/models/spree/order.rb:505:in `block in canceled_by'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/transactions.rb:220:in `transaction'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/transactions.rb:277:in `transaction'
vendor/bundle/ruby/2.2.0/gems/spree_core-3.0.4/app/models/spree/order.rb:504:in `canceled_by'
vendor/bundle/ruby/2.2.0/gems/spree_backend-3.0.4/app/controllers/spree/admin/orders_controller.rb:88:in `cancel'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/abstract_controller/base.rb:198:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:92:in `_run_callbacks'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/abstract_controller/base.rb:137:in `process'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.2/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal.rb:196:in `dispatch'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_controller/metal.rb:237:in `block in action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:74:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:43:in `serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:30:in `each'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:30:in `serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:819:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `public_send'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `method_missing'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/mapper.rb:51:in `serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:30:in `each'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:30:in `serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:819:in `call'
vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/flash.rb:260:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/query_cache.rb:36:in `call'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:88:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:88:in `_run_callbacks'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/rack/logger.rb:20:in `block in call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:68:in `tagged'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/rack/logger.rb:20:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/static.rb:113:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:164:in `call'
vendor/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/configuration.rb:78:in `call'
vendor/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:541:in `handle_request'
vendor/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:388:in `process_client'
vendor/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
vendor/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
vendor/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

### PR DESCRIPTION
**Pull request by shioyama**
Fixes #37

This adds cancel/void methods for credit card payments and also updates the AM gateway to actually send the amount to be refunded (otherwise it will always perform a full refund).

We are moving further away from the code on AM, we will have to make another PR there to sync up.

### CODE REVIEW

**Comment by shioyama** [comment]
Cancel:

latest-screenshot

**Comment by shioyama** [comment]
Partial refund:

latest-screenshot

On Komoju:

latest-screenshot

**Comment by shioyama** [comment]
Voided payment (treated as a refund on Komoju):

latest-screenshot

**Comment by shioyama** [comment]
@camelmasa want to check this one too :smile:

**Comment by camelmasa** [comment]
@shioyama Thanks I'm reviewing that :sunny:

**Comment by camelmasa** [comment]
@shioyama Almost those worked.  One point, it will occurs problem when purchased USD item and partial refunded that.

The redunded currency was JPY on komoju.

(test on local)
komoju_-_admin_-_vimperator

komoju_-_admin_-_vimperator

**Comment by camelmasa** [comment]
@shioyama I'll investigate that.

**Comment by shioyama** [comment]
Thanks!

**Comment by camelmasa** [comment]
@shioyama Sorry, that problem was not related spree_komoju. LGTM :+1: I'll merge it. :tada:

**Comment by shioyama** [comment]
Great thanks! I'll release a new version.

**Pull request merged**
