### PR TITLE
Add payment profiles support

### PR DESCRIPTION
**Pull request by shioyama**
This depends on activemerchant/active_merchant#1941, so we can't actually merge it until that PR is merged.

### CODE REVIEW

**Comment by shioyama** [comment]
I've included the komoju gateway from activemerchant here, which overrides anything in that gem and thus enables us to use payment profiles. Once AM merges the change we can remove this and just reference the latest version of the gem.

**Comment by shioyama** [comment]
@camelmasa can you check this? I think you're in the best position to do that.

**Comment by camelmasa** [comment]
@shioyama sure, I'll do that when after lunch :meat_on_bone:

**Comment by shioyama** [comment]
@camelmasa can I merge this?

**Comment by camelmasa** [comment]
@shioyama I was displayed following. Please check it :dancer: 

action_controller__exception_caught

**Comment by shioyama** [comment]
Thanks! I'll check that now.

**Comment by camelmasa** [comment]
@shioyama But, I tried that twice. I succeed that :(

order_r356911097_-_spree_demo_site

**Comment by shioyama** [comment]
Hmm I don't see that issue:

latest-screenshot

**Comment by shioyama** [comment]
Oh I see: https://github.com/camelmasa/spree_komoju/blob/8b5c2bb6aa2b83319cdca507e738dae6101b25cf/app/overrides/add_instruction_to_order_show.rb#L6

This won't work for other payment methods that don't have that method.

**Comment by shioyama** [comment]
@camelmasa I added the missing credit card spec, have a look.

**Comment by shioyama** [comment]
@camelmasa Ah wait I'll add one for `create_profile` as well.

**Comment by shioyama** [comment]
Ok everything is spec'ed now, have a look :smile:

**Comment by camelmasa** [comment]
@shioyama Tnank you for implementation. Please rename `Spree::BankTransfer#instruction_partial_path` too :pray:

**Comment by shioyama** [comment]
@camelmasa done!

**Comment by camelmasa** [comment]
@shioyama LGTM :100:

**Pull request merged**
