### PR TITLE
Add credit method to komoju credit card

### LINKED ISSUE #38: NoMethodError in Spree::Admin::RefundsController#create undefined method `credit' for #<ActiveMerchant::Billing::KomojuGateway:0x007fca9bd61bc8>
When trying to refund a payment in the admin backend to following error is raised:

NoMethodError in Spree::Admin::RefundsController#create undefined method `credit' for #<ActiveMerchant::Billing::KomojuGateway:0x007fca9bd61bc8>

### PR DESCRIPTION
**Pull request by shioyama**
Fixes #38

### CODE REVIEW

**Comment by shioyama** [comment]
Confirmed this fixes the issue:

latest-screenshot

And on Komoju:

latest-screenshot

**Comment by shioyama** [comment]
Don't merge yet, going to refactor spec code a bit.

**Comment by shioyama** [comment]
@camelmasa do you want to have a look at this? It's mostly your code I copy-pasted here :grin:

**Comment by camelmasa** [comment]
@shioyama LGTM :+1: Thanks :exclamation:

**Pull request merged**
