### PR TITLE
Add PayEasy to spree_komoju

### PR DESCRIPTION
**Pull request by rramsden**
This continues the work @camelmasa did in https://github.com/komoju/spree_komoju/pull/4

I've rebased his work on master and added some additional methods to make it work with the latest Spree. You can see my additional changes below.

### CODE REVIEW

**Comment by rramsden** [comment]
@camelmasa Do you mind reviewing this?

**Comment by camelmasa** [comment]
@rramsden Thank you for continuing :clap: I'll review that now.

**Comment by camelmasa** [comment]
@rramsden We need to add some `locale` words :dancers: 

spree_demo_site

`app/views/spree/orders/_pay_easy.html.erb` too.

Could you add locale of English :question: then I'm going to add locale of Japanese.

**Comment by rramsden** [comment]
@camelmasa I'll try and add now

**Comment by rramsden** [comment]
@camelmasa Could you take another look. Spree exception handling is very strange...

image

**Comment by camelmasa** [comment]
@rramsden LGTM :+1: Great work :star2:  Can I merge it :question:  Then I'd like to add japanese locale on other PR.

**Comment by rramsden** [comment]
@camelmasa Looks good to merge. Please add Japanese locales when you have time :pray:

**Pull request merged**
