### PR TITLE
Handle gateway timeouts

### PR DESCRIPTION
**Pull request by rramsden**
Resolves https://github.com/komoju/spree_komoju/issues/66

### CODE REVIEW

**Comment by rramsden** [comment]
@shioyama Can you take a look at this? @k2nr can you explain the CDN problem/solution and why its occurring.

**Comment by shioyama** [comment]
Sure will do

**Comment by rramsden** [comment]
Going to go ahead and merge this.

**Comment by shioyama** [comment]
Thanks, LGTM

**Pull request merged**
