### PR TITLE
Add source views and forms to spree admin

### PR DESCRIPTION
**Pull request by rramsden**
This pull requests adds missing source views for CreditCard, Konbini, BankTransfer, WebMoney, and PayEasy. I've managed to recycle the checkout forms used when creating payments in the spree admin dashboard.

A few bugs I found and fixed when adding these forms:

* We needed to permit attributes in Admin::PaymentsController for create orders via spree admin
* The Javascript code for WebMoney would not work in the admin dashboard because it was inside `frontend.js`. I've inlined the Javascript to be included with the webmoney partial now
* WebMoney was crashing because `can_capture?` was calling `expires_at` which the webmoney tables doesn't have because its a synchronous payment method.

### TODO

* Konbini, PayEasy, and Bank Transfer payments cannot be voided (we will need to disable this feature in spree)
* Creating a payment in spree admin doesnt not actually create a payment in Komoju. I'll need to investiage why this is today.

### CODE REVIEW

**Comment by rramsden** [comment]
@shioyama Think you could take a look? This just fixes the views in spree admin. There are a few other bugs related to "capturing" and "voiding" payments which I'll look into now.

**Comment by shioyama** [comment]
@camelmasa's going to have a look at it.

**Comment by camelmasa** [comment]
@rramsden > This just fixes the views in spree admin

I confirmed that. Yes, that was fixed now.
Please continue to investigate for fix other bugs.

**Comment by camelmasa** [comment]
@rramsden I checked that failed payment's prepaid number will be blank.

spree_ __

 Related those bugs :question: I don't know that.

**Comment by rramsden** [comment]
@camelmasa is that a bug or a feature? haha

**Comment by shioyama** [comment]
I'm getting an error about a missing method `with_public_profile` in `Spree::Konbini` on the new payments page, maybe my setup is different, just posting here for now:

latest-screenshot

**Comment by shioyama** [comment]
I'm not really sure maybe our setups are different, but when I started working on this I had to mess around with the `reusable_sources` method which is called in the payment form [here](https://github.com/spree/spree/blob/2f7322cdd764fd84bcb802eb157ad55118ff7ea0/backend/app/views/spree/admin/payments/_form.html.erb#L25). I'm not sure how it would render without doing something about that because [reusable_sources](https://github.com/spree/spree/blob/2f7322cdd764fd84bcb802eb157ad55118ff7ea0/core/app/models/spree/gateway.rb#L67) calls `sources_by_order` which assumes there is a scope `with_payment_profile` on the source (which does not exist for alternative payment methods). I had to add something there to get this view to render correctly for me.

Maybe my setup was different,  are you testing with `enable_customer_profiles` on or off? I'll keep digging.

**Comment by shioyama** [comment]
So I find that if I add these scopes + method to all Komoju payment methods (other than credit card) the issue is gone:

```ruby
scope :with_payment_profile, -> {}
scope :default, -> {}

def reusable_sources
  []
end
```

And actually about the latter method Spree mentions in a [comment](https://github.com/spree/spree/blob/2f7322cdd764fd84bcb802eb157ad55118ff7ea0/core/app/models/spree/payment_method.rb#L54) in the code that this should be overridden for custom gateways, so this makes sense, but I still don't understand how you guys didn't see it. Maybe our versions of spree or something are different? I'm running 3-0-stable (from the github branch), maybe that's the difference.

**Comment by shioyama** [comment]
Confirmed that I see the error with 3.0.4 as well, fixed with the method added.

**Comment by shioyama** [comment]
I also find that clicking "capture" on say a konbini payment does try to go to the gateway to capture it, but since there is no `capture` method on the activemerchant gateway it errors and falls through to `capture(stream)` in activesupport.

But actually I also see that when I create the konbini payment from the admin it *does* create it on Komoju, see below:

latest-screenshot

I can't capture it because of the issue above but that should just be a matter of aliasing `capture` to `purchase` or something in the konbini gateway. Not sure why we're seeing different things...

**Comment by shioyama** [comment]
So adding a method `capture` to the am gateway allows you to capture a konbini payment that has been authorized on komoju:

```ruby
def capture(money, payment, options = {})
  Response.new(true, "force captured")
end
```

Of course this does not mark the payment as captured on Komoju because we have no endpoint for doing that (normally it would only be captured when the customer actually pays, and in this case nobody has actually paid). So not sure if we actually want to allow this, but it does seem to work for me as expected.

**Comment by shioyama** [comment]
Actually I think we can just return `false` from `can_capture?` for all asynchronous methods (konbini, bank transfer, payeasy), since you should not be able to capture them manually from spree anywhere (just through the callback, which uses `payment.complete!` which is not affected by `can_capture?`). That way the capture buttons will not show for those payment methods and we don't have to worry about it.

We can also get rid of the void buttons for these payment methods by changing `can_void?` to just return `false` always.

**Comment by rramsden** [comment]
@shioyama thanks I was also thinking of just returning `can_capture?` since we can't capture directly from spree (they should be captured in Komoju). I will also set `can_void?` to false since out gateway doesn't support authorization/voiding.

**Comment by shioyama** [comment]
@rramsden actually also just redefining `actions` to remove those should do it I think.

**Comment by rramsden** [comment]
@shioyama I've removed `void` and `capture` actions from alternative payments

**Comment by shioyama** [comment]
Thanks!

**Pull request merged**
